// main entry point
// uk what layout does. Consistent across all pages
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/layouts/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen relative`}>
        <div className="absolute inset-0 m-auto w-9/10 h-4/5">
        <Header />
        {children}
        </div>
      </body>
    </html>
  );
};
