// main entry point
// uk what layout does. Consistent across all pages
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen justify-center items-center">
          <div className="h-4/5 flex items-center">
            {children}
          </div>
        </div>

        {/* <div className="container mx-auto">

          {children}
        </div> */}
      </body>

    </html>
  );
};
